- name: this is for conditions example to check user is exist or not
  hosts: localhost
  tasks:
  - name: check user exist or not
    # when you want to run linux commands directly i.e in the case ansible module not available
    # when the user does not exists, ansible treating this failure and comeout by default
    # ignore_errors: true
    ansible.builtin.command: id roboshop
    register: out #result will store in this variable
    ignore_errors: true
  - name: print result
    ansible.builtin.debug:
     msg: "USer is : {{out}}"
  - name: print status
    ansible.builtin.debug:
     msg: "status is :{{out.rc}}"    
  - when: out.rc != 0
    name: create user
    become: yes
    ansible.builtin.user:
     name: roboshop

#if this expression is true then only this module will run
