- name: install multiple packages through loops 
  hosts: localhost
  tasks:
  - name: install packages
    ansible.builtin.yum:
     name: "{{item}}"
     state: installed
    loop:
    - nginx
    - postfix
    - mailx
    - cyrus-sasl-plain