- name: intall packages
  hosts: localhost
  tasks:
  - name: install packages
    ansible.builtin.yum:
     name: "{{item.name}}"
     state: "{{item.state}}"
    loop:
    - {name: 'nginx', state: 'installed'}
    - {name: 'postfix', state: 'installed'}
    - {name: 'mailx', state: 'installed'}
    - {name: 'cyrus-sasl-plain', state: 'installed'} 
  - name: Make sure 'nginx' is started
    systemd:
     name: nginx
     state: started
     enabled: yes
    register: result

  - name: Show result
    ansible.builtin.debug:
     msg: "{{ result }}"